### ISSUE TITLE
Tiles are slightly off centered in one direction

### ISSUE THREAD

**Issue by SoraHjort** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#10]
First off: Thank you for working on this, it is much better than what is default for Foundry.

It is noticeable at grid sizes below 200px (such as the default 100px). In Columns mode, they are off centered towards the right by several pixels.
![image](https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/assets/18604504/c42d5abc-617c-4cf8-9a67-c5411963ca65)

And in Rows mode, they are off centered towards the bottom. 

![image](https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/assets/18604504/c7cf04c9-c3ef-4326-b137-10f23444c713)

It becomes extremely obvious when you try scaling it up so that the edge of the hexagon is close to the grid's lines, it begins to overlap the grid lines on the off centered sides.
![image](https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/assets/18604504/780c579e-e0b5-4d51-9a05-04bf768b8776)
![image](https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/assets/18604504/e79d2c3d-482f-4add-9ced-5834a6109b7d)

**Comment by hitcherland** [comment]
Fixed in 1.6, there was some funky business with rounding errors due to tiles being integers but the grid width being a float
