### ISSUE TITLE
Can't install on older foundry releases

### ISSUE THREAD

**Issue by BoltsJ** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#12]
On the foundry listing, every release points to the manifest in main, rather than the manifest for each version. This prevents users on v11 and earlier from installing via the package browser. Using the tagged manifest link, (e.g.
`https://raw.githubusercontent.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/1.6/module.json` for 1.6) for their respective version would allow easy installation for users on v11 and earlier.

![image](https://github.com/user-attachments/assets/a547c461-7238-4741-8c5b-924954bfb1ce)
https://foundryvtt.com/article/package-management/

**Comment by hitcherland** [comment]
Thanks for pointing that out! I have fixed versions for each 10, 11 & 12, and I'll keep it updated going forward
