### ISSUE TITLE
Installation link for FVTT error

### ISSUE THREAD

**Issue by FolkvangrForgent** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#2]
Currently FVTT tries to download ( https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/archive/refs/tags/1.0.zip ) however the actual link should be ( https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/archive/refs/tags/v1.0.zip ). This should be a quick change in the module.json

**Comment by hitcherland** [comment]
Argh, thanks for spotting that. I've update the tags so that the existing commit works. Installing from my instance of foundryvtt works, could you confirm that it's fixed for you?

**Comment by FolkvangrForgent** [comment]
Just wanted to confirm that your change fixed the issue.
