### ISSUE TITLE
Wrong manifest causes persistent re-download

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#5]
Since the last update to 1.3 the module always re-downloads on an update of the Foundry modules. Even though nothing changes. 
You can replicate that issue by updating the modules. Just updating Better Hexagonal Tiles also works, you can do it indefinitely.
That's likely because the latest release still has version 1.2 in the manifest (though I could be wrong about that).

**Comment by thorgibrewer** [comment]
I too am experiencing the same thing.

**Comment by linxcat** [comment]
@hitcherland https://github.com/hitcherland/FoundryVTT-Better-Hexagonal-Tiles/pull/6

**Comment by hitcherland** [comment]
Hopefully that is sorted now.
