### ISSUE TITLE
Compatibility warning

### ISSUE THREAD

**Issue by richardwilkes** [hitcherland/FoundryVTT-Better-Hexagonal-Tiles#7]
Using Foundry v10, I see the following warning in the console:

```
setup.js:145 [better-hexagonal-tiles] The module "better-hexagonal-tiles" is using "name" which is deprecated in favor of "id"
```

Truly minor, but would be nice to get this resolved.

**Comment by richardwilkes** [comment]
Forgot to mention this was with v1.3 of your module.

**Comment by hitcherland** [comment]
Strange! I can't see the same issues on my side, but I agree that it is deprecated. v1.4 should resolve it
